server:
  port: 8092
  servlet:
    context-path: /shiro

spring:
  application:
    name: shiro
  thymeleaf:
    cache: false #开发时关闭缓存,不然没法看到实时页面
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
  datasource:
    url: jdbc:mysql://localhost:3306/data01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.xilo.shiro.entity
  mapper-locations: classpath:com/xilo/shiro/dao/*.xml
  config-location: classpath:mybatis-config.xml
