server:
  port: 8092
  servlet:
    context-path: /shiro

spring:
  application:
    name: shiro
  thymeleaf:
    cache: false #开发时关闭缓存,不然没法看到实时页面
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html